---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: Ctactest.
    ansible_become_user: root
  tasks:
    - name: Install net-tools
      apt:
        name: net-tools
        state: present
        update_cache: yes
