- hosts: all
  become: yes
  vars:
    ansible_become_password: Ctactest
    ansible_become_user: administrator
  tasks:
    - name: Update apt repo
      apt:
        upgrade: yes
        update_cache: yes

